import { drizzle } from "drizzle-orm/neon-serverless";
import { Pool } from "@neondatabase/serverless";
import { iraqiHealthKnowledge } from "@shared/schema";
import { eq } from "drizzle-orm";

const pool = new Pool({ connectionString: process.env.DATABASE_URL!, max: 2 });
const db = drizzle(pool);

interface KnowledgeEntry {
  category: string;
  nameEn: string;
  nameAr: string;
  data: any;
  prevalenceRank?: number;
}

const DISEASES: KnowledgeEntry[] = [
  { category: "disease", nameEn: "Upper Respiratory Tract Infection", nameAr: "التهاب الجهاز التنفسي العلوي", prevalenceRank: 1, data: { icd10: "J06.9", commonSymptoms: ["sore throat", "cough", "runny nose", "fever"], seasonality: [10, 11, 12, 1, 2, 3], riskGroups: ["children", "elderly"], commonTreatment: ["Paracetamol", "Amoxicillin if bacterial"], localBrands: ["سامراء باراسيتامول", "اموكسيل"], notes: "Most common outpatient diagnosis in Iraq. Dust storms worsen symptoms." }},
  { category: "disease", nameEn: "Gastroenteritis", nameAr: "التهاب المعدة والأمعاء", prevalenceRank: 2, data: { icd10: "K52.9", commonSymptoms: ["diarrhea", "vomiting", "abdominal pain", "fever"], seasonality: [5, 6, 7, 8, 9], riskGroups: ["children", "elderly"], commonTreatment: ["ORS", "Metronidazole", "Ciprofloxacin"], localBrands: ["فلاجيل", "سيبروفلوكساسين"], notes: "Very common in summer due to contaminated water and food. Dehydration is major concern especially in children." }},
  { category: "disease", nameEn: "Type 2 Diabetes", nameAr: "السكري النوع الثاني", prevalenceRank: 3, data: { icd10: "E11", commonSymptoms: ["increased thirst", "frequent urination", "fatigue", "blurred vision"], seasonality: null, riskGroups: ["adults over 40", "obese", "family history"], commonTreatment: ["Metformin", "Glibenclamide", "Insulin"], localBrands: ["غلوكوفاج", "داونيل"], notes: "Iraq has one of the highest diabetes rates in the Middle East (~14% prevalence). Lifestyle and diet are major factors." }},
  { category: "disease", nameEn: "Hypertension", nameAr: "ارتفاع ضغط الدم", prevalenceRank: 4, data: { icd10: "I10", commonSymptoms: ["headache", "dizziness", "chest pain", "often asymptomatic"], seasonality: null, riskGroups: ["adults over 35", "obese", "smokers", "family history"], commonTreatment: ["Amlodipine", "Losartan", "Atenolol"], localBrands: ["نورفاسك", "كوزار", "تينورمين"], notes: "High prevalence in Iraq, often undiagnosed. Salt-heavy Iraqi diet contributes." }},
  { category: "disease", nameEn: "Allergic Rhinitis", nameAr: "التهاب الأنف التحسسي", prevalenceRank: 5, data: { icd10: "J30.4", commonSymptoms: ["sneezing", "runny nose", "itchy eyes", "nasal congestion"], seasonality: [3, 4, 5, 9, 10], riskGroups: ["all ages"], commonTreatment: ["Cetirizine", "Loratadine", "Fluticasone nasal spray"], localBrands: ["زيرتك", "كلاريتين"], notes: "Extremely common during dust storm season (spring/fall). Iraq's desert climate makes this prevalent." }},
  { category: "disease", nameEn: "Urinary Tract Infection", nameAr: "التهاب المسالك البولية", prevalenceRank: 6, data: { icd10: "N39.0", commonSymptoms: ["burning urination", "frequent urination", "lower abdominal pain", "cloudy urine"], seasonality: [6, 7, 8], riskGroups: ["women", "elderly", "diabetics"], commonTreatment: ["Ciprofloxacin", "Nitrofurantoin", "Trimethoprim"], localBrands: ["سيبروفلوكساسين", "يوفامين"], notes: "More common in summer due to dehydration. Higher rates in diabetic population." }},
  { category: "disease", nameEn: "Asthma", nameAr: "الربو", prevalenceRank: 7, data: { icd10: "J45", commonSymptoms: ["wheezing", "shortness of breath", "chest tightness", "cough at night"], seasonality: [3, 4, 5, 10, 11], riskGroups: ["children", "family history", "smokers"], commonTreatment: ["Salbutamol inhaler", "Budesonide", "Montelukast"], localBrands: ["فنتولين", "بولميكورت", "سينغولير"], notes: "Dust storms and air pollution in Iraqi cities exacerbate asthma significantly." }},
  { category: "disease", nameEn: "Iron Deficiency Anemia", nameAr: "فقر الدم بعوز الحديد", prevalenceRank: 8, data: { icd10: "D50", commonSymptoms: ["fatigue", "pale skin", "dizziness", "shortness of breath"], seasonality: null, riskGroups: ["women of reproductive age", "children", "pregnant women"], commonTreatment: ["Ferrous sulfate", "Folic acid", "Vitamin B12"], localBrands: ["فيروز", "فوليك اسيد"], notes: "Very common among Iraqi women and children. Dietary deficiency and parasitic infections contribute." }},
  { category: "disease", nameEn: "Peptic Ulcer Disease", nameAr: "قرحة المعدة", prevalenceRank: 9, data: { icd10: "K27", commonSymptoms: ["epigastric pain", "bloating", "nausea", "heartburn"], seasonality: null, riskGroups: ["adults", "smokers", "NSAID users", "stressed individuals"], commonTreatment: ["Omeprazole", "Ranitidine", "H. pylori triple therapy"], localBrands: ["لوسك", "اوميز", "زانتاك"], notes: "H. pylori prevalence in Iraq is very high (>70%). Stress and smoking are major contributors." }},
  { category: "disease", nameEn: "Bronchitis", nameAr: "التهاب القصبات", prevalenceRank: 10, data: { icd10: "J20", commonSymptoms: ["productive cough", "chest discomfort", "fatigue", "mild fever"], seasonality: [10, 11, 12, 1, 2], riskGroups: ["smokers", "elderly", "children"], commonTreatment: ["Amoxicillin", "Azithromycin", "Salbutamol"], localBrands: ["اموكسيل", "زيثروماكس"], notes: "Common in winter. Smoking rates in Iraq are high, contributing to chronic bronchitis." }},
  { category: "disease", nameEn: "Conjunctivitis", nameAr: "التهاب الملتحمة", prevalenceRank: 11, data: { icd10: "H10", commonSymptoms: ["red eyes", "itching", "discharge", "tearing"], seasonality: [3, 4, 5, 6], riskGroups: ["children", "contact lens users"], commonTreatment: ["Tobramycin eye drops", "Chloramphenicol eye drops"], localBrands: ["توبرامايسين قطرة", "كلورامفينيكول قطرة"], notes: "Common during dust storms and spring allergies." }},
  { category: "disease", nameEn: "Brucellosis", nameAr: "الحمى المالطية", prevalenceRank: 12, data: { icd10: "A23", commonSymptoms: ["undulating fever", "joint pain", "sweating", "fatigue", "back pain"], seasonality: [4, 5, 6, 7], riskGroups: ["farmers", "herders", "raw dairy consumers"], commonTreatment: ["Doxycycline + Streptomycin", "Doxycycline + Rifampicin"], localBrands: ["دوكسيسايكلين", "ريفامبيسين"], notes: "Endemic in Iraq due to livestock contact and consumption of unpasteurized dairy (gaymer, laban). Common in rural areas." }},
  { category: "disease", nameEn: "Typhoid Fever", nameAr: "حمى التيفوئيد", prevalenceRank: 13, data: { icd10: "A01.0", commonSymptoms: ["sustained high fever", "headache", "abdominal pain", "constipation or diarrhea"], seasonality: [6, 7, 8, 9], riskGroups: ["all ages", "poor sanitation areas"], commonTreatment: ["Ciprofloxacin", "Azithromycin", "Ceftriaxone"], localBrands: ["سيبروفلوكساسين", "زيثروماكس"], notes: "Still endemic in parts of Iraq due to water contamination. More common in summer." }},
  { category: "disease", nameEn: "Cutaneous Leishmaniasis", nameAr: "اللشمانيا الجلدية (حبة بغداد)", prevalenceRank: 14, data: { icd10: "B55.1", commonSymptoms: ["skin ulcer", "painless nodule", "scarring"], seasonality: [5, 6, 7, 8, 9, 10], riskGroups: ["rural populations", "children"], commonTreatment: ["Sodium stibogluconate", "Cryotherapy"], localBrands: ["بنتوستام"], notes: "Known locally as 'حبة بغداد' (Baghdad Boil). Endemic in central/southern Iraq. Sandfly vector active in warm months." }},
  { category: "disease", nameEn: "Tuberculosis", nameAr: "السل", prevalenceRank: 15, data: { icd10: "A15", commonSymptoms: ["chronic cough", "night sweats", "weight loss", "hemoptysis"], seasonality: null, riskGroups: ["overcrowded areas", "immunocompromised", "malnourished"], commonTreatment: ["RHZE regimen (Rifampicin, Isoniazid, Pyrazinamide, Ethambutol)"], localBrands: ["ريفامبيسين", "ايزونيازيد"], notes: "Iraq has moderate TB prevalence. MDR-TB is a growing concern." }},
  { category: "disease", nameEn: "Eczema / Atopic Dermatitis", nameAr: "الأكزيما", prevalenceRank: 16, data: { icd10: "L20", commonSymptoms: ["itchy skin", "dry patches", "redness", "scaling"], seasonality: [10, 11, 12, 1, 2], riskGroups: ["children", "family history of atopy"], commonTreatment: ["Hydrocortisone cream", "Emollients", "Cetirizine"], localBrands: ["هيدروكورتيزون كريم", "زيرتك"], notes: "Common in Iraqi children. Dry winter air and dust worsen symptoms." }},
  { category: "disease", nameEn: "Migraine", nameAr: "الصداع النصفي", prevalenceRank: 17, data: { icd10: "G43", commonSymptoms: ["severe headache", "nausea", "light sensitivity", "aura"], seasonality: null, riskGroups: ["women", "family history", "stressed individuals"], commonTreatment: ["Paracetamol", "Ibuprofen", "Sumatriptan"], localBrands: ["سامراء باراسيتامول", "بروفين", "اميجران"], notes: "Common, often triggered by stress, dehydration, and intense sun exposure in Iraqi summers." }},
  { category: "disease", nameEn: "Kidney Stones", nameAr: "حصى الكلى", prevalenceRank: 18, data: { icd10: "N20", commonSymptoms: ["severe flank pain", "hematuria", "nausea", "urinary urgency"], seasonality: [5, 6, 7, 8, 9], riskGroups: ["men", "dehydration-prone", "family history"], commonTreatment: ["Diclofenac", "Tamsulosin", "Hydration"], localBrands: ["فولتارين", "تامسولين"], notes: "Very common in Iraq due to hot climate and inadequate water intake. Prevalence peaks in summer." }},
  { category: "disease", nameEn: "Dental Caries/Infections", nameAr: "تسوس وعدوى الأسنان", prevalenceRank: 19, data: { icd10: "K02", commonSymptoms: ["toothache", "swelling", "sensitivity", "bad breath"], seasonality: null, riskGroups: ["all ages", "poor oral hygiene"], commonTreatment: ["Amoxicillin", "Metronidazole", "Ibuprofen"], localBrands: ["اموكسيل", "فلاجيل", "بروفين"], notes: "Extremely common. Many Iraqis delay dental care. Antibiotics often sought before dental visits." }},
  { category: "disease", nameEn: "Depression/Anxiety", nameAr: "الاكتئاب/القلق", prevalenceRank: 20, data: { icd10: "F32/F41", commonSymptoms: ["persistent sadness", "loss of interest", "sleep disturbance", "fatigue", "worry"], seasonality: null, riskGroups: ["conflict-affected", "women", "unemployed youth"], commonTreatment: ["Sertraline", "Escitalopram", "CBT referral"], localBrands: ["زولوفت", "لوسترال"], notes: "Significantly underdiagnosed in Iraq. Conflict, displacement, and economic stress are major drivers. Stigma prevents many from seeking help." }},
  { category: "disease", nameEn: "Tonsillitis", nameAr: "التهاب اللوزتين", prevalenceRank: 21, data: { icd10: "J03", commonSymptoms: ["sore throat", "difficulty swallowing", "fever", "enlarged tonsils"], seasonality: [10, 11, 12, 1, 2, 3], riskGroups: ["children ages 5-15"], commonTreatment: ["Amoxicillin", "Azithromycin", "Paracetamol"], localBrands: ["اموكسيل", "زيثروماكس", "سامراء باراسيتامول"], notes: "Very common in Iraqi schoolchildren during winter." }},
  { category: "disease", nameEn: "Heat Stroke/Exhaustion", nameAr: "ضربة الشمس/الإنهاك الحراري", prevalenceRank: 22, data: { icd10: "T67", commonSymptoms: ["high body temperature", "confusion", "hot dry skin", "rapid pulse", "headache"], seasonality: [6, 7, 8, 9], riskGroups: ["outdoor workers", "elderly", "children"], commonTreatment: ["Rapid cooling", "IV fluids", "Emergency care"], localBrands: [], notes: "Critical summer hazard in Iraq where temperatures exceed 50°C. Power outages worsen risk. Education on prevention is crucial." }},
  { category: "disease", nameEn: "Vitamin D Deficiency", nameAr: "نقص فيتامين د", prevalenceRank: 23, data: { icd10: "E55", commonSymptoms: ["bone pain", "muscle weakness", "fatigue", "frequent infections"], seasonality: null, riskGroups: ["women (covered clothing)", "elderly", "children"], commonTreatment: ["Cholecalciferol (Vitamin D3)", "Calcium supplements"], localBrands: ["فيدروب", "كالسيوم-د"], notes: "Paradoxically very common in sunny Iraq. Women in full covering are especially at risk. >60% deficiency rate reported." }},
  { category: "disease", nameEn: "Otitis Media", nameAr: "التهاب الأذن الوسطى", prevalenceRank: 24, data: { icd10: "H66", commonSymptoms: ["ear pain", "fever", "hearing loss", "ear discharge"], seasonality: [10, 11, 12, 1, 2], riskGroups: ["children under 5", "smokers' children"], commonTreatment: ["Amoxicillin", "Paracetamol", "Ear drops"], localBrands: ["اموكسيل", "سامراء باراسيتامول"], notes: "Common pediatric condition. Often follows upper respiratory infections." }},
  { category: "disease", nameEn: "Scabies", nameAr: "الجرب", prevalenceRank: 25, data: { icd10: "B86", commonSymptoms: ["intense itching (worse at night)", "rash", "burrows on skin"], seasonality: [10, 11, 12, 1, 2], riskGroups: ["overcrowded living", "children", "displaced populations"], commonTreatment: ["Permethrin cream", "Ivermectin"], localBrands: ["بيرمثرين كريم", "ايفرمكتين"], notes: "Endemic in overcrowded areas and IDP camps. Whole family treatment needed." }},
];

const MEDICINES: KnowledgeEntry[] = [
  { category: "medicine", nameEn: "Paracetamol (Samarra)", nameAr: "سامراء باراسيتامول", prevalenceRank: 1, data: { generic: "Paracetamol/Acetaminophen", manufacturer: "SDI Samarra", forms: ["500mg tablets", "120mg/5ml syrup", "250mg suppositories"], uses: ["fever", "pain", "headache"], iraqiPrice: "~2,000-5,000 IQD", availability: "universal", notes: "Most widely used OTC medicine in Iraq" }},
  { category: "medicine", nameEn: "Brufen (Ibuprofen)", nameAr: "بروفين", prevalenceRank: 2, data: { generic: "Ibuprofen", manufacturer: "Abbott", forms: ["400mg tablets", "200mg tablets", "100mg/5ml syrup"], uses: ["pain", "inflammation", "fever", "arthritis"], iraqiPrice: "~5,000-10,000 IQD", availability: "universal", notes: "Preferred NSAID brand in Iraq" }},
  { category: "medicine", nameEn: "Amoxil (Amoxicillin)", nameAr: "اموكسيل", prevalenceRank: 3, data: { generic: "Amoxicillin", manufacturer: "GSK/Local", forms: ["500mg capsules", "250mg capsules", "250mg/5ml suspension"], uses: ["bacterial infections", "ear infections", "UTI", "dental infections"], iraqiPrice: "~5,000-15,000 IQD", availability: "universal", notes: "Most commonly prescribed antibiotic in Iraq" }},
  { category: "medicine", nameEn: "Augmentin (Amox/Clav)", nameAr: "اوغمنتين", prevalenceRank: 4, data: { generic: "Amoxicillin/Clavulanate", manufacturer: "GSK", forms: ["625mg tablets", "1g tablets", "312mg/5ml suspension"], uses: ["resistant bacterial infections", "sinusitis", "pneumonia"], iraqiPrice: "~15,000-25,000 IQD", availability: "wide", notes: "Second-line antibiotic widely used in Iraq" }},
  { category: "medicine", nameEn: "Azithromycin (Zithromax)", nameAr: "زيثروماكس", prevalenceRank: 5, data: { generic: "Azithromycin", manufacturer: "Pfizer/Local", forms: ["500mg tablets", "200mg/5ml suspension"], uses: ["respiratory infections", "skin infections", "STIs"], iraqiPrice: "~10,000-20,000 IQD", availability: "wide", notes: "Popular for 3-day course convenience" }},
  { category: "medicine", nameEn: "Ciprofloxacin", nameAr: "سيبروفلوكساسين", prevalenceRank: 6, data: { generic: "Ciprofloxacin", manufacturer: "Various", forms: ["500mg tablets", "250mg tablets"], uses: ["UTI", "GI infections", "typhoid"], iraqiPrice: "~5,000-12,000 IQD", availability: "wide", notes: "Commonly used for GI and urinary infections in Iraq" }},
  { category: "medicine", nameEn: "Metronidazole (Flagyl)", nameAr: "فلاجيل", prevalenceRank: 7, data: { generic: "Metronidazole", manufacturer: "Sanofi/Local", forms: ["500mg tablets", "250mg tablets"], uses: ["amoebic dysentery", "dental infections", "bacterial vaginosis", "H. pylori"], iraqiPrice: "~3,000-8,000 IQD", availability: "universal", notes: "Very commonly used for GI infections in Iraq. Often used with amoxicillin for dental infections." }},
  { category: "medicine", nameEn: "Omeprazole (Losec/Omez)", nameAr: "لوسك / اوميز", prevalenceRank: 8, data: { generic: "Omeprazole", manufacturer: "AstraZeneca/Dr Reddy's", forms: ["20mg capsules", "40mg capsules"], uses: ["GERD", "peptic ulcer", "H. pylori therapy"], iraqiPrice: "~5,000-15,000 IQD", availability: "universal", notes: "PPI widely used given high H. pylori prevalence in Iraq" }},
  { category: "medicine", nameEn: "Glucophage (Metformin)", nameAr: "غلوكوفاج", prevalenceRank: 9, data: { generic: "Metformin", manufacturer: "Merck", forms: ["500mg tablets", "850mg tablets", "1000mg tablets"], uses: ["type 2 diabetes"], iraqiPrice: "~5,000-12,000 IQD", availability: "universal", notes: "First-line diabetes treatment. Very high demand given Iraq's diabetes prevalence." }},
  { category: "medicine", nameEn: "Amlodipine (Norvasc)", nameAr: "نورفاسك", prevalenceRank: 10, data: { generic: "Amlodipine", manufacturer: "Pfizer/Local", forms: ["5mg tablets", "10mg tablets"], uses: ["hypertension", "angina"], iraqiPrice: "~5,000-15,000 IQD", availability: "wide", notes: "Common antihypertensive in Iraq" }},
  { category: "medicine", nameEn: "Cetirizine (Zyrtec)", nameAr: "زيرتك", prevalenceRank: 11, data: { generic: "Cetirizine", manufacturer: "UCB/Local", forms: ["10mg tablets", "5mg/5ml syrup"], uses: ["allergic rhinitis", "urticaria", "hay fever"], iraqiPrice: "~3,000-8,000 IQD", availability: "universal", notes: "Essential during dust storm season in Iraq" }},
  { category: "medicine", nameEn: "Salbutamol (Ventolin)", nameAr: "فنتولين", prevalenceRank: 12, data: { generic: "Salbutamol/Albuterol", manufacturer: "GSK", forms: ["inhaler 100mcg", "nebulizer solution", "2mg/5ml syrup"], uses: ["asthma", "bronchospasm", "COPD"], iraqiPrice: "~8,000-15,000 IQD", availability: "wide", notes: "Essential rescue inhaler. High demand during dust storms." }},
  { category: "medicine", nameEn: "Diclofenac (Voltaren)", nameAr: "فولتارين", prevalenceRank: 13, data: { generic: "Diclofenac", manufacturer: "Novartis/Local", forms: ["50mg tablets", "75mg IM injection", "gel"], uses: ["pain", "inflammation", "arthritis", "kidney stones"], iraqiPrice: "~3,000-10,000 IQD", availability: "universal", notes: "Very popular NSAID in Iraq, both oral and injectable forms" }},
  { category: "medicine", nameEn: "Ceftriaxone (Rocephin)", nameAr: "روسيفين", prevalenceRank: 14, data: { generic: "Ceftriaxone", manufacturer: "Roche/Local", forms: ["1g vial IM/IV", "250mg vial"], uses: ["severe infections", "meningitis", "typhoid", "pneumonia"], iraqiPrice: "~10,000-25,000 IQD", availability: "hospital/clinic", notes: "Common injectable antibiotic in Iraqi hospitals and clinics" }},
  { category: "medicine", nameEn: "Doxycycline", nameAr: "دوكسيسايكلين", prevalenceRank: 15, data: { generic: "Doxycycline", manufacturer: "Various", forms: ["100mg capsules"], uses: ["brucellosis", "acne", "respiratory infections", "malaria prophylaxis"], iraqiPrice: "~5,000-10,000 IQD", availability: "wide", notes: "Key drug for brucellosis treatment which is endemic in Iraq" }},
  { category: "medicine", nameEn: "Prednisolone", nameAr: "بريدنيزولون", prevalenceRank: 16, data: { generic: "Prednisolone", manufacturer: "Various", forms: ["5mg tablets", "15mg/5ml syrup"], uses: ["asthma exacerbation", "allergic reactions", "autoimmune conditions"], iraqiPrice: "~3,000-8,000 IQD", availability: "wide", notes: "Commonly used for acute asthma and severe allergic reactions" }},
  { category: "medicine", nameEn: "Ranitidine (Zantac)", nameAr: "زانتاك", prevalenceRank: 17, data: { generic: "Ranitidine", manufacturer: "GSK/Local", forms: ["150mg tablets", "300mg tablets"], uses: ["GERD", "peptic ulcer", "heartburn"], iraqiPrice: "~3,000-8,000 IQD", availability: "wide", notes: "H2 blocker alternative to PPIs. Still widely used in Iraq despite global recalls of some brands." }},
  { category: "medicine", nameEn: "Losartan (Cozaar)", nameAr: "كوزار", prevalenceRank: 18, data: { generic: "Losartan", manufacturer: "MSD/Local", forms: ["50mg tablets", "100mg tablets"], uses: ["hypertension", "diabetic nephropathy"], iraqiPrice: "~8,000-15,000 IQD", availability: "wide", notes: "ARB commonly used in hypertensive diabetic patients" }},
  { category: "medicine", nameEn: "Atorvastatin (Lipitor)", nameAr: "ليبيتور", prevalenceRank: 19, data: { generic: "Atorvastatin", manufacturer: "Pfizer/Local", forms: ["10mg tablets", "20mg tablets", "40mg tablets"], uses: ["hypercholesterolemia", "cardiovascular prevention"], iraqiPrice: "~8,000-20,000 IQD", availability: "wide", notes: "Increasingly prescribed as cardiovascular disease awareness grows" }},
  { category: "medicine", nameEn: "Insulin (various)", nameAr: "انسولين", prevalenceRank: 20, data: { generic: "Insulin (Regular, NPH, Glargine)", manufacturer: "Novo Nordisk/Sanofi", forms: ["vials", "pens"], uses: ["type 1 diabetes", "type 2 diabetes (advanced)"], iraqiPrice: "~15,000-50,000 IQD", availability: "pharmacy/hospital", notes: "Critical for many Iraqi diabetics. Government subsidizes some insulin. Supply chain issues common." }},
  { category: "medicine", nameEn: "Ibufen (Ibuprofen)", nameAr: "ايبوفين", prevalenceRank: 21, data: { generic: "Ibuprofen", manufacturer: "SDI Samarra", forms: ["400mg tablets", "100mg/5ml syrup"], uses: ["pain", "fever", "inflammation"], iraqiPrice: "~2,000-5,000 IQD", availability: "universal", notes: "Local Iraqi brand of ibuprofen, cheaper alternative to Brufen" }},
  { category: "medicine", nameEn: "Glibenclamide (Daonil)", nameAr: "داونيل", prevalenceRank: 22, data: { generic: "Glibenclamide", manufacturer: "Sanofi", forms: ["5mg tablets"], uses: ["type 2 diabetes"], iraqiPrice: "~3,000-8,000 IQD", availability: "wide", notes: "Sulfonylurea widely used alongside metformin in Iraq" }},
  { category: "medicine", nameEn: "Montelukast (Singulair)", nameAr: "سينغولير", prevalenceRank: 23, data: { generic: "Montelukast", manufacturer: "MSD/Local", forms: ["10mg tablets", "4mg chewable", "5mg chewable"], uses: ["asthma prevention", "allergic rhinitis"], iraqiPrice: "~10,000-20,000 IQD", availability: "wide", notes: "Popular add-on therapy for asthma and allergies" }},
  { category: "medicine", nameEn: "ORS (Oral Rehydration Salts)", nameAr: "أملاح الإرواء الفموي", prevalenceRank: 24, data: { generic: "ORS (WHO formula)", manufacturer: "Various/Local", forms: ["sachets for 1L"], uses: ["dehydration", "diarrhea", "vomiting", "heat exhaustion"], iraqiPrice: "~500-2,000 IQD", availability: "universal", notes: "Life-saving for pediatric gastroenteritis. Available at all pharmacies. Essential summer supply." }},
  { category: "medicine", nameEn: "Loperamide (Imodium)", nameAr: "ايموديوم", prevalenceRank: 25, data: { generic: "Loperamide", manufacturer: "Johnson & Johnson/Local", forms: ["2mg capsules"], uses: ["acute diarrhea"], iraqiPrice: "~3,000-8,000 IQD", availability: "universal", notes: "Very popular OTC antidiarrheal in Iraq" }},
  { category: "medicine", nameEn: "Mebendazole (Vermox)", nameAr: "فيرموكس", prevalenceRank: 26, data: { generic: "Mebendazole", manufacturer: "Janssen/Local", forms: ["100mg tablets", "100mg/5ml suspension"], uses: ["intestinal worms", "pinworms", "roundworms"], iraqiPrice: "~2,000-5,000 IQD", availability: "universal", notes: "Commonly used in Iraqi children for parasitic infections" }},
  { category: "medicine", nameEn: "Cephalexin (Keflex)", nameAr: "كيفلكس", prevalenceRank: 27, data: { generic: "Cephalexin", manufacturer: "Various", forms: ["500mg capsules", "250mg/5ml suspension"], uses: ["skin infections", "UTI", "respiratory infections"], iraqiPrice: "~5,000-12,000 IQD", availability: "wide", notes: "First-generation cephalosporin commonly used in Iraq" }},
  { category: "medicine", nameEn: "Domperidone (Motilium)", nameAr: "موتيليوم", prevalenceRank: 28, data: { generic: "Domperidone", manufacturer: "Janssen/Local", forms: ["10mg tablets", "suspension"], uses: ["nausea", "vomiting", "gastroparesis"], iraqiPrice: "~3,000-8,000 IQD", availability: "wide", notes: "Popular antiemetic in Iraq, available OTC" }},
  { category: "medicine", nameEn: "Chlorpheniramine", nameAr: "كلورفينيرامين", prevalenceRank: 29, data: { generic: "Chlorpheniramine", manufacturer: "Various", forms: ["4mg tablets", "2mg/5ml syrup"], uses: ["allergic rhinitis", "common cold", "urticaria"], iraqiPrice: "~1,000-3,000 IQD", availability: "universal", notes: "Cheap first-generation antihistamine, widely used OTC" }},
  { category: "medicine", nameEn: "Tramadol", nameAr: "ترامادول", prevalenceRank: 30, data: { generic: "Tramadol", manufacturer: "Various", forms: ["50mg capsules", "100mg tablets"], uses: ["moderate-severe pain"], iraqiPrice: "~5,000-12,000 IQD", availability: "prescription only", notes: "Controlled substance. Abuse is a growing concern in Iraq. Prescription required." }},
];

const SEASONAL_PATTERNS: KnowledgeEntry[] = [
  { category: "seasonal_pattern", nameEn: "Summer Heat Illnesses", nameAr: "أمراض حرارة الصيف", prevalenceRank: 1, data: { months: [6, 7, 8, 9], description: "Extreme heat (45-52°C) causes heat stroke, dehydration, kidney stones, UTIs. Power outages worsen risk. Advise adequate hydration (3-4L/day), avoid midday sun, ORS for children.", descriptionAr: "الحرارة الشديدة (٤٥-٥٢ درجة) تسبب ضربة الشمس والجفاف وحصى الكلى والتهابات المسالك البولية. انقطاع الكهرباء يزيد الخطر. يُنصح بشرب ٣-٤ لتر ماء يومياً وتجنب الشمس وقت الظهيرة.", riskLevel: "high", preventionTips: ["Drink 3-4 liters of water daily", "Avoid outdoor activity 11am-4pm", "Keep ORS sachets at home", "Watch for confusion/dry skin in elderly"] }},
  { category: "seasonal_pattern", nameEn: "Dust Storm Respiratory Issues", nameAr: "مشاكل تنفسية من العواصف الرملية", prevalenceRank: 2, data: { months: [3, 4, 5, 6, 9, 10], description: "Frequent dust storms trigger asthma attacks, allergic rhinitis, conjunctivitis, and bronchitis exacerbations. PM10 levels can exceed 1000 μg/m³.", descriptionAr: "العواصف الرملية المتكررة تسبب نوبات الربو والتهاب الأنف التحسسي والتهاب الملتحمة وتفاقم التهاب الشعب الهوائية. مستويات الغبار قد تتجاوز الحدود الآمنة بكثير.", riskLevel: "high", preventionTips: ["Keep rescue inhaler accessible", "Stay indoors during storms", "Use damp cloth over nose/mouth", "Seal windows and doors", "Antihistamines for allergy sufferers"] }},
  { category: "seasonal_pattern", nameEn: "Winter Respiratory Infections", nameAr: "التهابات الجهاز التنفسي الشتوية", prevalenceRank: 3, data: { months: [11, 12, 1, 2, 3], description: "Cold weather increases URTIs, influenza, bronchitis, and tonsillitis. Overcrowded indoor spaces facilitate transmission.", descriptionAr: "الطقس البارد يزيد التهابات الجهاز التنفسي العلوي والإنفلونزا والتهاب الشعب الهوائية والتهاب اللوزتين. الأماكن المغلقة المزدحمة تسهّل انتقال العدوى.", riskLevel: "moderate", preventionTips: ["Get flu vaccination", "Wash hands frequently", "Ventilate indoor spaces", "Keep children warm", "Paracetamol for fever management"] }},
  { category: "seasonal_pattern", nameEn: "Summer Gastroenteritis", nameAr: "التهاب المعدة والأمعاء الصيفي", prevalenceRank: 4, data: { months: [5, 6, 7, 8, 9], description: "Food spoilage, water contamination, and fly-borne transmission cause spikes in gastroenteritis, typhoid, and food poisoning.", descriptionAr: "فساد الطعام وتلوث المياه والذباب تسبب ارتفاعاً في التهاب المعدة والأمعاء والتيفوئيد والتسمم الغذائي.", riskLevel: "high", preventionTips: ["Refrigerate food properly", "Boil water if unsure of source", "Wash produce thoroughly", "Keep ORS at home for children", "Seek care early for bloody diarrhea"] }},
  { category: "seasonal_pattern", nameEn: "Spring Allergy Season", nameAr: "موسم حساسية الربيع", prevalenceRank: 5, data: { months: [3, 4, 5], description: "Pollen from date palms, grasses, and flowers triggers allergic rhinitis and asthma. Coincides with dust storm season for double impact.", descriptionAr: "حبوب لقاح النخيل والأعشاب والأزهار تسبب التهاب الأنف التحسسي والربو. يتزامن مع موسم العواصف الرملية مما يضاعف التأثير.", riskLevel: "moderate", preventionTips: ["Start antihistamines early in season", "Avoid outdoor exercise during high pollen times", "Keep windows closed", "Shower after outdoor exposure"] }},
  { category: "seasonal_pattern", nameEn: "Brucellosis Season", nameAr: "موسم الحمى المالطية", prevalenceRank: 6, data: { months: [4, 5, 6, 7], description: "Spring birthing season increases brucellosis risk through animal contact and consumption of unpasteurized dairy products (gaymer, raw laban).", descriptionAr: "موسم ولادة الحيوانات في الربيع يزيد خطر الحمى المالطية من خلال ملامسة الحيوانات واستهلاك منتجات الألبان غير المبسترة (القيمر واللبن الخام).", riskLevel: "moderate", preventionTips: ["Avoid unpasteurized dairy", "Use gloves when handling livestock", "Cook meat thoroughly", "Seek care for undulating fever + joint pain"] }},
  { category: "seasonal_pattern", nameEn: "Leishmaniasis Active Season", nameAr: "موسم اللشمانيا النشط", prevalenceRank: 7, data: { months: [5, 6, 7, 8, 9, 10], description: "Sandfly activity peaks in warm months. Cutaneous leishmaniasis (Baghdad Boil) cases increase, especially in central/southern Iraq.", descriptionAr: "نشاط ذبابة الرمل يبلغ ذروته في الأشهر الحارة. تزداد حالات اللشمانيا الجلدية (حبة بغداد)، خاصة في وسط وجنوب العراق.", riskLevel: "moderate", preventionTips: ["Use insect repellent at dusk", "Sleep under treated nets", "Report non-healing skin ulcers", "Keep environment clean to reduce sandfly breeding"] }},
  { category: "seasonal_pattern", nameEn: "Ramadan Health Considerations", nameAr: "اعتبارات صحية في رمضان", prevalenceRank: 8, data: { months: [3, 4], description: "Fasting affects medication timing, hydration, and blood sugar management. Diabetic patients need adjusted medication schedules. Dehydration risk if Ramadan falls in summer.", descriptionAr: "الصيام يؤثر على مواعيد الأدوية والترطيب وإدارة سكر الدم. مرضى السكري يحتاجون تعديل مواعيد أدويتهم. خطر الجفاف إذا صادف رمضان فصل الصيف.", riskLevel: "moderate", preventionTips: ["Consult doctor about medication timing during fasting", "Diabetics: monitor blood sugar more frequently", "Hydrate well between iftar and suhoor", "Avoid heavy meals at iftar", "Break fast if feeling unwell"] }},
];

const REGIONAL_HEALTH: KnowledgeEntry[] = [
  { category: "regional_health", nameEn: "Baghdad", nameAr: "بغداد", prevalenceRank: 1, data: { population: "~8 million", topConditions: ["respiratory infections", "diabetes", "hypertension", "GI infections", "depression/anxiety"], environmentalFactors: ["air pollution", "dust storms", "urban overcrowding", "traffic accidents"], healthcareAccess: "Best access to tertiary care. Medical City, Teaching Hospital, Ibn Sina Hospital. Many private clinics in Mansour, Karrada.", notes: "Highest healthcare density but also highest population. Urban lifestyle diseases predominate." }},
  { category: "regional_health", nameEn: "Basra", nameAr: "البصرة", prevalenceRank: 2, data: { population: "~3 million", topConditions: ["respiratory diseases", "cancer clusters", "waterborne diseases", "heat-related illness"], environmentalFactors: ["extreme heat (55°C+)", "water salination", "oil industry pollution", "depleted uranium legacy"], healthcareAccess: "Basra Teaching Hospital, limited specialist care. Many travel to Baghdad for complex cases.", notes: "Water quality crisis. Higher cancer rates reported. Extreme summer heat makes dehydration/heat stroke major concerns." }},
  { category: "regional_health", nameEn: "Erbil (Kurdistan)", nameAr: "أربيل (كردستان)", prevalenceRank: 3, data: { population: "~2 million", topConditions: ["diabetes", "hypertension", "respiratory infections", "vitamin D deficiency"], environmentalFactors: ["cold winters", "rapid urbanization", "dietary changes"], healthcareAccess: "Better funded healthcare system. Rizgary Hospital, PAR Hospital. Growing private sector. Many international NGO clinics.", notes: "Kurdistan Region has relatively better healthcare infrastructure. Growing lifestyle disease burden from urbanization." }},
  { category: "regional_health", nameEn: "Mosul", nameAr: "الموصل", prevalenceRank: 4, data: { population: "~2 million", topConditions: ["trauma/PTSD", "respiratory infections", "waterborne diseases", "malnutrition"], environmentalFactors: ["post-conflict infrastructure damage", "water system damage", "overcrowded displacement camps"], healthcareAccess: "Severely damaged by conflict. Al-Khansaa Hospital rebuilt. Many clinics operated by WHO/MSF. Limited specialist care.", notes: "Healthcare system still recovering from conflict. Mental health needs are enormous. Infrastructure rebuilding ongoing." }},
  { category: "regional_health", nameEn: "Southern Rural Iraq", nameAr: "جنوب العراق الريفي", prevalenceRank: 5, data: { population: "~5 million across provinces", topConditions: ["brucellosis", "leishmaniasis", "GI parasites", "malnutrition", "snake/scorpion bites"], environmentalFactors: ["limited water/sanitation", "livestock contact", "limited healthcare access", "extreme heat"], healthcareAccess: "Primary health centers (PHCs) are main access point. Long distances to hospitals. Traditional medicine still practiced.", notes: "Rural populations face significant healthcare access barriers. Many rely on PHCs and traditional healers." }},
];

const CULTURAL_PRACTICES: KnowledgeEntry[] = [
  { category: "cultural_practice", nameEn: "Self-medication and antibiotic overuse", nameAr: "التداوي الذاتي وفرط استخدام المضادات الحيوية", prevalenceRank: 1, data: { description: "Iraqis commonly self-prescribe antibiotics from pharmacies without prescriptions. This contributes to antibiotic resistance. Pharmacists often dispense antibiotics on request.", clinicalImplication: "Ask about recent antibiotic use. Consider resistance patterns. Educate about completing courses and avoiding unnecessary antibiotics.", frequency: "very common" }},
  { category: "cultural_practice", nameEn: "Traditional remedies alongside modern medicine", nameAr: "العلاجات التقليدية إلى جانب الطب الحديث", prevalenceRank: 2, data: { description: "Many Iraqis use herbal remedies: habba sawda (black seed), honey, cupping (hijama), herbal teas (chamomile, anise). Often used alongside prescribed medications.", clinicalImplication: "Ask about traditional remedies to check for interactions. Don't dismiss traditional practices but ensure safety. Black seed oil can interact with blood thinners and diabetes medications.", frequency: "common" }},
  { category: "cultural_practice", nameEn: "Delayed medical seeking in women", nameAr: "تأخر طلب المرأة للرعاية الطبية", prevalenceRank: 3, data: { description: "Cultural norms may cause women to delay seeking medical care, especially for sensitive issues. Many prefer female doctors. Some need male family member's approval.", clinicalImplication: "Create a supportive, non-judgmental assessment environment. Be sensitive to privacy concerns. Offer reassurance about confidentiality.", frequency: "common" }},
  { category: "cultural_practice", nameEn: "Religious and spiritual healing", nameAr: "العلاج الروحي والديني", prevalenceRank: 4, data: { description: "Some patients attribute illness to spiritual causes (ain/evil eye, hasad/envy). May seek religious healers (mullahs, sheikhs) before or alongside medical care.", clinicalImplication: "Respect beliefs while ensuring medical treatment is not delayed. Frame medical treatment as complementary to spiritual practices, not contradictory.", frequency: "moderate" }},
  { category: "cultural_practice", nameEn: "Family-centric healthcare decisions", nameAr: "قرارات الرعاية الصحية المتمركزة حول العائلة", prevalenceRank: 5, data: { description: "Healthcare decisions are often made collectively by the family, especially for women, children, and elderly. The eldest male may have final say on treatment plans.", clinicalImplication: "Include family context in care recommendations. Provide information that can be shared with family decision-makers. Respect family dynamics.", frequency: "very common" }},
];

const HEALTHCARE_SYSTEM: KnowledgeEntry[] = [
  { category: "healthcare_system", nameEn: "Public Healthcare Structure", nameAr: "هيكل الرعاية الصحية العامة", prevalenceRank: 1, data: { description: "Iraq has a tiered public system: Primary Health Centers (PHCs) → District Hospitals → Teaching/Specialist Hospitals. Public care is nominally free but often lacks supplies.", tiers: ["Primary Health Centers (PHCs) - basic care, vaccinations", "District/General Hospitals - emergency, inpatient", "Teaching Hospitals - specialist care, complex cases"], notes: "Long wait times. Many patients go directly to emergency departments bypassing PHCs." }},
  { category: "healthcare_system", nameEn: "Private Sector Growth", nameAr: "نمو القطاع الخاص", prevalenceRank: 2, data: { description: "Private clinics and hospitals growing rapidly, especially in Baghdad, Erbil, Sulaymaniyah. Offer faster service but at cost. Quality varies significantly.", cost: "Consultation: 25,000-75,000 IQD. Lab tests: 10,000-50,000 IQD. Imaging: 50,000-200,000 IQD.", notes: "Many Iraqis use private for initial consultation, public for hospitalization/surgery." }},
  { category: "healthcare_system", nameEn: "Pharmacy Practice", nameAr: "ممارسة الصيدلة", prevalenceRank: 3, data: { description: "Pharmacies are often the first point of care. Pharmacists prescribe and dispense medications, including antibiotics, without prescription. Many pharmacies open late.", dispensingPractices: ["Antibiotics dispensed without prescription", "Injection services offered", "Basic health advice given", "Often first stop before doctor"], notes: "Pharmacists play a huge role in Iraqi healthcare. App should consider them as primary care touchpoint." }},
];

export async function seedIraqiKnowledge(): Promise<void> {
  try {
    const [existing] = await db.select({ count: iraqiHealthKnowledge.id })
      .from(iraqiHealthKnowledge).limit(1);
    
    if (existing) {
      console.log("Iraqi health knowledge already seeded, skipping...");
      return;
    }

    const allEntries: KnowledgeEntry[] = [
      ...DISEASES,
      ...MEDICINES,
      ...SEASONAL_PATTERNS,
      ...REGIONAL_HEALTH,
      ...CULTURAL_PRACTICES,
      ...HEALTHCARE_SYSTEM,
    ];

    for (const entry of allEntries) {
      await db.insert(iraqiHealthKnowledge).values({
        category: entry.category,
        nameEn: entry.nameEn,
        nameAr: entry.nameAr,
        data: JSON.stringify(entry.data),
        prevalenceRank: entry.prevalenceRank || null,
        isActive: true,
      });
    }

    console.log(`Seeded ${allEntries.length} Iraqi health knowledge entries`);
  } catch (err) {
    console.error("Seed error:", err instanceof Error ? err.message : "Unknown");
  }
}
